apiVersion: v1
kind: Service
metadata:
  name: service-{{.Replica}} 
  labels:
    group: load
    kube-burner-job: api-intensive
spec:
  selector:
    name: api-intensive-{{.Replica}}
  ports:
  - port: 80
    targetPort: 80
